version: '3.6'

services:
  dashboard:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional but required for Docker integration
    # ports:
    #   - 5005:5005
    # secrets:
      # - password # optional but required for (1)
    environment:
      - PASSWORD=Oncoming Victory Tribesman Trapped
      # - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped
    networks:
     - traefik
    labels:
      - traefik.http.routers.dashboard.rule=Host(`dashboard.christopherenea.net`)
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.services.dashboard.loadbalancer.server.port=5005
      - traefik.http.routers.dashboard.tls.certresolver=myresolver
      - traefik.port=443

# optional but required for Docker secrets (1)
# secrets:
#   password:
#     file: /path/to/secrets/password

volumes:
  flame:

networks:
  traefik:
    name: traefik
    external: true