version: '3'

volumes:
  rss-cache:

services:
  full-text-rss:
    image: heussd/fivefilters-full-text-rss:latest
    container_name: full-text-rss
    restart: unless-stopped
    labels:
      - traefik.http.routers.full-text-rss.rule=Host(`full-text-rss.christopherenea.net`)
      - traefik.http.routers.full-text-rss.tls=true
      - traefik.http.services.full-text-rss.loadbalancer.server.port=80
      - traefik.port=80
    networks:
      - traefik
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache"

  fresh-rss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: fresh-rss
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /etc/fresh-rss:/config
    labels:
      - traefik.http.routers.fresh-rss.rule=Host(`fresh-rss.christopherenea.net`)
      - traefik.http.routers.fresh-rss.tls=true
      - traefik.http.services.fresh-rss.loadbalancer.server.port=80
      - traefik.port=443
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
