version: '3'

volumes:
  fresh-rss-data:
    driver: local

services:
  full-text-rss:
    image: heussd/fivefilters-full-text-rss:latest
    container_name: full-text-rss
    restart: unless-stopped
    ports:
      - "50000:80"
    labels:
      - traefik.http.routers.full-text-rss.rule=Host(`full-text-rss.christopherenea.net`)
      - traefik.http.routers.full-text-rss.tls=false
      - traefik.port=80
      - traefik.http.services.full-text-rss.loadbalancer.server.port=80

  fresh-rss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: fresh-rss
    restart: unless-stopped
    ports:
      - "49999:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /etc/fresh-rss:/config
    labels:
      - traefik.http.routers.fresh-rss.rule=Host(`fresh-rss.christopherenea.net`)
      - traefik.http.routers.fresh-rss.tls=false
      - traefik.port=80
      - traefik.http.services.fresh-rss.loadbalancer.server.port=80