version: '3'

services:
  reverse-proxy:
    container_name: "traefik"
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: 
     - "--api.insecure=true" 
     - "--providers.docker"
     - "--entrypoints.websecure.address=:443"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.christopherenea.net`)
      - traefik.http.routers.traefik.tls=false
      - traefik.port=80
      - traefik.http.services.traefik.loadbalancer.server.port=8080

networks:
  traefik:
    name: traefik